name: 'Comment on PR'
on:
  pull_request:
    branches-ignore:    
      - dev
      - '!hotfix/**'
      - '!release/**'

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: comment PR if needed
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
           message: 'Thank you for the master PR. We only accept dev and hotfix PRs for master branch. Please switch base branch to dev to get reviewed'
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}