on:
  pull_request:
    branches:    
      - 'master/**'

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: comment PR if needed
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1

        with:
          message: 'Thank you for the master pull request. We do not accept feature branches for master branches'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}